services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data_volume:/home/node/.n8n
    # depends_on:
    #   - postgres
    networks:
      - n8n_network
    restart: unless-stopped

  # postgres:
  #   image: postgres:13
  #   container_name: postgres_n8n
  #   environment:
  #     - POSTGRES_USER=${DB_POSTGRESDB_USER}
  #     - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
  #     - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - n8n_network
  #   restart: unless-stopped

volumes:
  n8n_data_volume:
    name: n8n_data_volume

networks:
  n8n_network:
    name: n8n_network
    driver: bridge